// libs/markstream-vue/packages/markstream-react/src/components/FootnoteReferenceNode/FootnoteReferenceNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback, useMemo } from 'react'

export function FootnoteReferenceNode(props: NodeComponentProps<{ type: 'footnote_reference', id: string }>) {
  const { node } = props
  const href = useMemo(() => `#footnote-${node.id}`, [node.id])
  const handleScroll = useCallback((event: React.MouseEvent) => {
    event.preventDefault()
    if (typeof document === 'undefined')
      return
    const target = document.querySelector(href)
    if (target)
      target.scrollIntoView({ behavior: 'smooth' })
  }, [href])

  return (
    <sup id={`fnref-${node.id}`} className="footnote-reference" onClick={handleScroll}>
      <a href={href} title={`View footnote ${node.id}`} className="footnote-link cursor-pointer">
        [
        {node.id}
        ]
      </a>
    </sup>
  )
}

export default FootnoteReferenceNode

// libs/markstream-vue/src/components/FootnoteReferenceNode/FootnoteReferenceNode.vue
<script setup lang="ts">
// 定义脚注引用节点
interface FootnoteReferenceNode {
  type: 'footnote_reference'
  id: string
  raw: string
}

// 接收props
const props = defineProps<{
  node: FootnoteReferenceNode
}>()
const href = `#footnote-${props.node.id}`
function handleScroll() {
  if (typeof document === 'undefined') {
    // SSR: nothing to do
    return
  }
  const element = document.querySelector(href)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
  else {
    console.warn(`Element with href: ${href} not found`)
  }
}
</script>

<template>
  <sup :id="`fnref-${node.id}`" class="footnote-reference" @click="handleScroll">
    <span
      :href="href"
      :title="`查看脚注 ${node.id}`"
      class="footnote-link cursor-pointer"
    >[{{ node.id }}]</span>
  </sup>
</template>

<style scoped>
.footnote-reference {
  font-size: 0.75em;
  line-height: 0;
}

.footnote-link {
  color: var(--link-color);
  text-decoration: none;
}

.footnote-link:hover {
  text-decoration: underline;
}
</style>
