// libs/markstream-vue/packages/markstream-angular/src/components/TableNode/TableNode.component.ts
import type { ElementRef, OnDestroy } from '@angular/core'
import type { AngularRenderableNode, AngularRenderContext } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, ChangeDetectorRef, Component, forwardRef, inject, Input, ViewChild } from '@angular/core'
import { NestedRendererComponent } from '../NestedRenderer/NestedRenderer.component'
import { getNodeList, getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-table-node',
  standalone: true,
  imports: [CommonModule, forwardRef(() => NestedRendererComponent)],
  template: `
    <table #tableElement>
      <colgroup *ngIf="columnWidths.length > 0">
        <col
          *ngFor="let cell of headerCells; let cellIndex = index; trackBy: trackCell"
          [style.width.px]="columnWidths[cellIndex] || null"
        >
      </colgroup>
      <thead *ngIf="headerRow">
        <tr>
          <ng-container *ngFor="let cell of headerCells; let cellIndex = index; trackBy: trackCell">
            <th [style.text-align]="alignment(cell) || null">
              <markstream-angular-nested-renderer
                [nodes]="childrenFor(cell)"
                [context]="context"
                [indexPrefix]="cellPrefix('head', cellIndex)"
              />
              <button
                *ngIf="cellIndex < headerCells.length - 1"
                type="button"
                class="table-node__resize-handle"
                [attr.aria-label]="'Resize columns ' + (cellIndex + 1) + ' and ' + (cellIndex + 2)"
                (pointerdown)="startColumnResize(cellIndex, $event)"
              ></button>
            </th>
          </ng-container>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let row of rows; let rowIndex = index; trackBy: trackRow">
          <ng-container *ngFor="let cell of cellsFor(row); let cellIndex = index; trackBy: trackCell">
            <td [style.text-align]="alignment(cell) || null">
              <markstream-angular-nested-renderer
                [nodes]="childrenFor(cell)"
                [context]="context"
                [indexPrefix]="cellPrefix(rowIndex, cellIndex)"
              />
            </td>
          </ng-container>
        </tr>
      </tbody>
    </table>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableNodeComponent implements OnDestroy {
  @ViewChild('tableElement') tableElement?: ElementRef<HTMLTableElement>

  private readonly cdr = inject(ChangeDetectorRef)
  private currentHeaderCellCount = 0
  private readonly minColumnWidth = 48
  private resizeState: {
    index: number
    startX: number
    startWidth: number
    nextStartWidth: number
    widths: number[]
  } | null = null

  columnWidths: number[] = []

  private _node!: AngularRenderableNode

  @Input({ required: true })
  set node(value: AngularRenderableNode) {
    this._node = value
    const count = this.headerCells.length
    if (count !== this.currentHeaderCellCount) {
      this.stopColumnResize()
      this.columnWidths = []
      this.currentHeaderCellCount = count
    }
  }

  get node() {
    return this._node
  }

  @Input() context?: AngularRenderContext
  @Input() indexKey?: string

  get headerRow() {
    const row = (this.node as any)?.header
    return row && typeof row === 'object' ? row as AngularRenderableNode : null
  }

  get headerCells() {
    return this.headerRow ? this.cellsFor(this.headerRow) : []
  }

  get rows() {
    return getNodeList((this.node as any)?.rows)
  }

  cellsFor(row: AngularRenderableNode) {
    return getNodeList((row as any)?.cells)
  }

  childrenFor(cell: AngularRenderableNode) {
    return getNodeList((cell as any)?.children)
  }

  alignment(cell: AngularRenderableNode) {
    return getString((cell as any)?.align)
  }

  trackRow = (index: number) => {
    return `${this.indexKey || 'table'}-row-${index}`
  }

  trackCell = (index: number) => {
    return index
  }

  cellPrefix(rowIndex: string | number, cellIndex: number) {
    return `${this.indexKey || 'table'}-${rowIndex}-${cellIndex}`
  }

  startColumnResize(index: number, event: PointerEvent) {
    if (event.button !== 0)
      return

    const widths = this.measureHeaderWidths()
    const startWidth = widths[index]
    const nextStartWidth = widths[index + 1]
    if (!startWidth || !nextStartWidth)
      return

    event.preventDefault()
    this.stopColumnResize()

    this.resizeState = {
      index,
      startX: event.clientX,
      startWidth,
      nextStartWidth,
      widths,
    }
    this.columnWidths = widths
    this.cdr.markForCheck()

    window.addEventListener('pointermove', this.onColumnResizeMove)
    window.addEventListener('pointerup', this.stopColumnResize)
    window.addEventListener('pointercancel', this.stopColumnResize)
  }

  ngOnDestroy() {
    this.stopColumnResize()
  }

  private measureHeaderWidths() {
    const cells = this.tableElement?.nativeElement.querySelectorAll('thead th')
    return Array.from(cells ?? [], cell => Math.round(cell.getBoundingClientRect().width))
  }

  private onColumnResizeMove = (event: PointerEvent) => {
    if (!this.resizeState)
      return

    event.preventDefault()

    const pairWidth = this.resizeState.startWidth + this.resizeState.nextStartWidth
    const minWidth = Math.min(this.minColumnWidth, Math.floor(pairWidth / 2))
    const width = Math.max(
      minWidth,
      Math.min(pairWidth - minWidth, Math.round(this.resizeState.startWidth + event.clientX - this.resizeState.startX)),
    )
    const nextWidths = [...this.resizeState.widths]
    nextWidths[this.resizeState.index] = width
    nextWidths[this.resizeState.index + 1] = pairWidth - width
    this.columnWidths = nextWidths
    this.cdr.markForCheck()
  }

  private stopColumnResize = () => {
    if (!this.resizeState)
      return

    window.removeEventListener('pointermove', this.onColumnResizeMove)
    window.removeEventListener('pointerup', this.stopColumnResize)
    window.removeEventListener('pointercancel', this.stopColumnResize)
    this.resizeState = null
  }
}

// libs/markstream-vue/packages/markstream-react/src/components/TableNode/TableNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import clsx from 'clsx'
import React from 'react'
import { renderInline } from '../../renderers/renderChildren'

export function TableNode(props: NodeComponentProps<{ type: 'table', header?: any, rows?: any[], loading?: boolean }>) {
  const { node, ctx, renderNode, indexKey } = props
  const headerCells = Array.isArray(node?.header?.cells) ? node.header.cells : []
  const isLoading = Boolean(node?.loading)
  const bodyRows = Array.isArray(node?.rows) ? node.rows : []
  const tableRef = React.useRef<HTMLTableElement | null>(null)
  const resizeStateRef = React.useRef<{
    index: number
    startX: number
    startWidth: number
    nextStartWidth: number
    widths: number[]
  } | null>(null)
  const resizeListenersRef = React.useRef<{
    move: (event: PointerEvent) => void
    stop: () => void
  } | null>(null)
  const [columnWidths, setColumnWidths] = React.useState<number[]>([])

  const minColumnWidth = 48

  const getAlignClass = (align?: string) => {
    if (align === 'right')
      return 'text-right'
    if (align === 'center')
      return 'text-center'
    return 'text-left'
  }

  const measureHeaderWidths = () => {
    const cells = tableRef.current?.querySelectorAll('thead th')
    return Array.from(cells ?? [], cell => Math.round(cell.getBoundingClientRect().width))
  }

  const stopColumnResize = () => {
    const listeners = resizeListenersRef.current
    if (listeners) {
      window.removeEventListener('pointermove', listeners.move)
      window.removeEventListener('pointerup', listeners.stop)
      window.removeEventListener('pointercancel', listeners.stop)
      resizeListenersRef.current = null
    }
    resizeStateRef.current = null
  }

  const startColumnResize = (index: number, event: React.PointerEvent<HTMLButtonElement>) => {
    if (event.button !== 0)
      return

    const widths = measureHeaderWidths()
    const startWidth = widths[index]
    const nextStartWidth = widths[index + 1]
    if (!startWidth || !nextStartWidth)
      return

    event.preventDefault()
    stopColumnResize()

    resizeStateRef.current = {
      index,
      startX: event.clientX,
      startWidth,
      nextStartWidth,
      widths,
    }
    setColumnWidths(widths)

    const move = (moveEvent: PointerEvent) => {
      const resizeState = resizeStateRef.current
      if (!resizeState)
        return

      moveEvent.preventDefault()

      const pairWidth = resizeState.startWidth + resizeState.nextStartWidth
      const minWidth = Math.min(minColumnWidth, Math.floor(pairWidth / 2))
      const width = Math.max(
        minWidth,
        Math.min(pairWidth - minWidth, Math.round(resizeState.startWidth + moveEvent.clientX - resizeState.startX)),
      )
      const nextWidths = [...resizeState.widths]
      nextWidths[resizeState.index] = width
      nextWidths[resizeState.index + 1] = pairWidth - width
      setColumnWidths(nextWidths)
    }
    const stop = () => {
      stopColumnResize()
    }

    resizeListenersRef.current = { move, stop }
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', stop)
    window.addEventListener('pointercancel', stop)
  }

  React.useEffect(() => {
    stopColumnResize()
    setColumnWidths([])

    return stopColumnResize
  }, [headerCells.length])

  return (
    <div className="table-node-wrapper" data-index-key={indexKey}>
      <table
        ref={tableRef}
        className={clsx(
          'my-8 text-sm table-node',
          isLoading && 'table-node--loading',
        )}
        aria-busy={isLoading}
      >
        {columnWidths.length > 0 && (
          <colgroup>
            {headerCells.map((_: any, idx: number) => (
              <col key={`col-${idx}`} style={columnWidths[idx] > 0 ? { width: `${columnWidths[idx]}px` } : undefined} />
            ))}
          </colgroup>
        )}
        <thead className="border-[var(--table-border,#cbd5e1)]">
          <tr className="border-b">
            {headerCells.map((cell: any, idx: number) => (
              <th
                key={`header-${idx}`}
                className={clsx('font-semibold p-[calc(4/7*1em)]', getAlignClass(cell.align))}
                dir="auto"
              >
                {ctx && renderNode ? renderInline(cell.children, ctx, `${String(indexKey ?? 'table')}-th-${idx}`, renderNode) : null}
                {idx < headerCells.length - 1 && (
                  <button
                    type="button"
                    className="table-node__resize-handle"
                    aria-label={`Resize columns ${idx + 1} and ${idx + 2}`}
                    onPointerDown={event => startColumnResize(idx, event)}
                  />
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {bodyRows.map((row: any, rowIdx: number) => (
            <tr
              key={`row-${rowIdx}`}
              className={clsx(
                'border-[var(--table-border,#cbd5e1)]',
                rowIdx < bodyRows.length - 1 && 'border-b',
              )}
            >
              {row.cells?.map((cell: any, cellIdx: number) => (
                <td
                  key={`cell-${rowIdx}-${cellIdx}`}
                  className={clsx('p-[calc(4/7*1em)]', getAlignClass(cell.align))}
                  dir="auto"
                >
                  {ctx && renderNode ? renderInline(cell.children, ctx, `${String(indexKey ?? 'table')}-row-${rowIdx}-${cellIdx}`, renderNode) : null}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      {isLoading && (
        <div className="table-node__loading" role="status" aria-live="polite">
          <span className="table-node__spinner" aria-hidden="true" />
          <span className="sr-only">Loading</span>
        </div>
      )}
    </div>
  )
}

export default TableNode
