// libs/markstream-vue/src/components/ReferenceNode/ReferenceNode.vue
<script setup lang="ts">
defineProps<{
  node: {
    type: 'reference'
    id: string
    raw: string
  }
  messageId?: string
  threadId?: string
}>()
defineEmits(['click', 'mouseEnter', 'mouseLeave'])
</script>

<template>
  <span
    class="reference-node cursor-pointer text-xs rounded-md px-1.5 mx-0.5"
    role="button"
    tabindex="0"
    @click="$emit('click', $event, node.id, messageId, threadId)"
    @mouseenter="$emit('mouseEnter', $event, node.id, messageId, threadId)"
    @mouseleave="$emit('mouseLeave', $event, node.id, messageId, threadId)"
  >
    {{ node.id }}
  </span>
</template>

<style scoped>
.reference-node {
  background-color: hsl(var(--ms-muted));
  color: hsl(var(--ms-muted-foreground));
}

.reference-node:hover {
  background-color: hsl(var(--ms-secondary));
}
</style>

// libs/markstream-vue/packages/markstream-react/src/components/ReferenceNode/ReferenceNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback } from 'react'

export interface ReferenceNodeHandlers {
  onClick?: (event: React.MouseEvent, id: string, messageId?: string, threadId?: string) => void
  onMouseEnter?: (event: React.MouseEvent, id: string, messageId?: string, threadId?: string) => void
  onMouseLeave?: (event: React.MouseEvent, id: string, messageId?: string, threadId?: string) => void
}

export function ReferenceNode(
  props: NodeComponentProps<{ type: 'reference', id: string }>
    & { messageId?: string, threadId?: string }
    & ReferenceNodeHandlers,
) {
  const { node } = props
  const handleClick = useCallback((event: React.MouseEvent) => {
    props.onClick?.(event, node.id, props.messageId, props.threadId)
  }, [node.id, props])

  return (
    <span
      className="reference-node cursor-pointer bg-[hsl(var(--muted))] text-xs rounded-md px-1.5 mx-0.5 hover:bg-[hsl(var(--secondary))]"
      role="button"
      tabIndex={0}
      onClick={handleClick}
      onMouseEnter={(event) => {
        props.onMouseEnter?.(event, node.id, props.messageId, props.threadId)
      }}
      onMouseLeave={(event) => {
        props.onMouseLeave?.(event, node.id, props.messageId, props.threadId)
      }}
      onKeyDown={(event) => {
        if (event.key === 'Enter' || event.key === ' ')
          handleClick(event as any)
      }}
    >
      {node.id}
    </span>
  )
}

export default ReferenceNode
