// libs/markstream-vue/packages/markstream-react/src/components/CodeBlockNode/HtmlPreviewFrame.tsx
import React, { useEffect, useMemo } from 'react'
import { createPortal } from 'react-dom'
import { useSafeI18n } from '../../i18n/useSafeI18n'

export interface HtmlPreviewFrameProps {
  code: string
  isDark?: boolean
  onClose?: () => void
  title?: string
}

export function HtmlPreviewFrame(props: HtmlPreviewFrameProps) {
  const { t } = useSafeI18n()
  const srcdoc = useMemo(() => {
    const base = props.code || ''
    const lowered = base.trim().toLowerCase()
    if (lowered.startsWith('<!doctype') || lowered.startsWith('<html') || lowered.startsWith('<body'))
      return base
    const bg = props.isDark ? '#020617' : '#ffffff'
    const fg = props.isDark ? '#e5e7eb' : '#020617'
    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        background-color: ${bg};
        color: ${fg};
      }
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'SF Pro Text', ui-sans-serif, sans-serif;
      }
    </style>
  </head>
  <body>
    ${base}
  </body>
</html>`
  }, [props.code, props.isDark])

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' || event.key === 'Esc')
        props.onClose?.()
    }
    if (typeof window !== 'undefined')
      window.addEventListener('keydown', handleKeydown)
    return () => {
      if (typeof window !== 'undefined')
        window.removeEventListener('keydown', handleKeydown)
    }
  }, [props])

  if (typeof document === 'undefined')
    return null

  return createPortal(
    <div className={`html-preview-frame__backdrop${props.isDark ? ' html-preview-frame__backdrop--dark' : ''}`} onClick={() => props.onClose?.()}>
      <div className={`html-preview-frame${props.isDark ? ' html-preview-frame--dark' : ''}`} onClick={e => e.stopPropagation()}>
        <div className="html-preview-frame__header">
          <div className="html-preview-frame__title">
            <span className="html-preview-frame__dot" />
            <span className="html-preview-frame__label">{props.title || `HTML ${t('common.preview')}`}</span>
          </div>
          <button
            type="button"
            className={`html-preview-frame__close${props.isDark ? ' html-preview-frame__close--dark' : ''}`}
            onClick={() => props.onClose?.()}
          >
            ×
          </button>
        </div>
        <iframe
          className="html-preview-frame__iframe"
          sandbox="allow-scripts allow-same-origin"
          src="about:blank"
          srcDoc={srcdoc}
          title={props.title || 'Preview'}
        />
      </div>
    </div>,
    document.body,
  )
}

export default HtmlPreviewFrame

// libs/markstream-vue/src/components/CodeBlockNode/HtmlPreviewFrame.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue'
import { useSafeI18n } from '../../composables/useSafeI18n'

const props = defineProps<{
  code: string
  isDark?: boolean
  onClose?: () => void
  title?: string
}>()

const { t } = useSafeI18n()

const srcdoc = computed(() => {
  const base = props.code || ''
  // 如果用户已经自己写了 <html>/<body>，直接原样输出，避免重复包裹
  const lowered = base.trim().toLowerCase()
  if (lowered.startsWith('<!doctype') || lowered.startsWith('<html') || lowered.startsWith('<body'))
    return base

  const bg = props.isDark ? '#020617' : '#ffffff'
  const fg = props.isDark ? '#e5e7eb' : '#020617'

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        background-color: ${bg};
        color: ${fg};
      }
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'SF Pro Text', ui-sans-serif, sans-serif;
      }
    </style>
  </head>
  <body>
    ${base}
  </body>
</html>`
})

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' || e.key === 'Esc')
    props.onClose?.()
}

onMounted(() => {
  if (typeof window !== 'undefined')
    window.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  if (typeof window !== 'undefined')
    window.removeEventListener('keydown', handleKeydown)
})
</script>

<template>
  <teleport to="body">
    <div class="markstream-vue" :class="{ dark: props.isDark }">
      <div class="html-preview-frame__backdrop" @click="props.onClose?.()">
        <div class="html-preview-frame" @click.stop>
          <div class="html-preview-frame__header">
            <div class="html-preview-frame__title">
              <span class="html-preview-frame__dot" />
              <span class="html-preview-frame__label">{{ props.title || t('common.preview') || 'Preview' }}</span>
            </div>
            <button
              type="button"
              class="html-preview-frame__close"
              @click="props.onClose?.()"
            >
              ×
            </button>
          </div>
          <iframe
            class="html-preview-frame__iframe"
            sandbox="allow-scripts allow-same-origin"
            :srcdoc="srcdoc"
          />
        </div>
      </div>
    </div>
  </teleport>
</template>

<style scoped>
.html-preview-frame__backdrop {
  position: fixed;
  inset: 0;
  background-color: var(--modal-overlay);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 50;
}

.html-preview-frame {
  width: 80vw;
  max-width: 960px;
  height: 70vh;
  background-color: var(--modal-bg);
  color: var(--modal-fg);
  border-radius: calc(var(--ms-radius) * 2);
  overflow: hidden;
  box-shadow: var(--ms-shadow-preview);
  display: flex;
  flex-direction: column;
}

.html-preview-frame__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.4rem 0.75rem;
  border-bottom: 1px solid var(--code-border);
}

.html-preview-frame__title {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.75rem;
  font-weight: 500;
  letter-spacing: 0.02em;
  text-transform: uppercase;
  opacity: 0.85;
}

.html-preview-frame__dot {
  width: 0.5rem;
  height: 0.5rem;
  border-radius: 999px;
  background-color: hsl(var(--ms-success));
}

.html-preview-frame__label {
  white-space: nowrap;
}

.html-preview-frame__close {
  border: none;
  background: transparent;
  font-size: 1.25rem;
  line-height: 1;
  cursor: pointer;
  color: var(--modal-fg);
}

.html-preview-frame__iframe {
  width: 100%;
  height: 100%;
  border: none;
  display: block;
}

@media (max-width: 640px) {
  .html-preview-frame {
    width: 100vw;
    height: 80vh;
    border-radius: 0;
  }
}
</style>
