// libs/markstream-vue/packages/markstream-angular/src/components/MathBlockNode/MathBlockNode.component.ts
import type { AfterViewInit, ElementRef, OnChanges, OnDestroy } from '@angular/core'
import type { AngularRenderableNode } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  inject,
  Input,
  ViewChild,
} from '@angular/core'
import { getKatex } from '../../optional/katex'
import { normalizeKaTeXRenderInput } from '../../utils/normalizeKaTeXRenderInput'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-math-block-node',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="math-block markstream-nested-math-block" data-markstream-katex-managed="1">
      <div #mathRef class="markstream-nested-math-block__render" [class.math-rendering]="rendering"></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MathBlockNodeComponent implements AfterViewInit, OnChanges, OnDestroy {
  private readonly cdr = inject(ChangeDetectorRef)

  @ViewChild('mathRef') private mathRef?: ElementRef<HTMLDivElement>

  @Input({ required: true }) node!: AngularRenderableNode

  rendering = true

  private destroyed = false
  private renderVersion = 0
  private hasRenderedOnce = false

  get content() {
    return getString((this.node as any)?.content || (this.node as any)?.markup || (this.node as any)?.raw)
  }

  ngAfterViewInit() {
    void this.renderMath()
  }

  ngOnChanges() {
    if (!this.mathRef)
      return
    void this.renderMath()
  }

  ngOnDestroy() {
    this.destroyed = true
    this.renderVersion += 1
  }

  private async renderMath() {
    const target = this.mathRef?.nativeElement
    if (!target)
      return

    const content = normalizeKaTeXRenderInput(this.content)
    const version = ++this.renderVersion
    if (!content) {
      target.textContent = ''
      this.rendering = false
      this.cdr.markForCheck()
      return
    }

    if (!this.hasRenderedOnce)
      this.rendering = true

    const html = await this.resolveKatexMarkup(content)
    if (this.destroyed || version !== this.renderVersion)
      return

    if (html) {
      target.innerHTML = html
      this.hasRenderedOnce = true
      this.rendering = false
    }
    else if (!(this.node as any)?.loading) {
      target.textContent = getString((this.node as any)?.raw || content)
      this.rendering = false
    }

    this.cdr.markForCheck()
  }

  private async resolveKatexMarkup(content: string) {
    try {
      return await renderKaTeXWithBackpressure(content, true, {
        timeout: 3000,
        waitTimeout: 2000,
        maxRetries: 1,
      })
    }
    catch (error: any) {
      const code = error?.code || error?.name
      const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || error?.fallbackToRenderer
      const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
      if (!isWorkerInitFailure && !isBusyOrTimeout)
        return null
    }

    const katex = await getKatex()
    if (!katex)
      return null

    try {
      const html = katex.renderToString(content, {
        throwOnError: (this.node as any)?.loading === true,
        displayMode: true,
      })
      setKaTeXCache(content, true, html)
      return html
    }
    catch {
      return null
    }
  }
}

// libs/markstream-vue/packages/markstream-react/src/components/Math/MathBlockNode.tsx
import type { VisibilityHandle } from '../../context/viewportPriority'
import type { MathBlockNodeProps } from '../../types/component-props'
import { useEffect, useRef, useState } from 'react'
import { useViewportPriority } from '../../context/viewportPriority'
import { normalizeKaTeXRenderInput } from '../../utils/normalizeKaTeXRenderInput'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import { getKatex } from './katex'

export function MathBlockNode({ node }: MathBlockNodeProps) {
  const containerRef = useRef<HTMLDivElement | null>(null)
  const mathRef = useRef<HTMLDivElement | null>(null)
  const viewportHandleRef = useRef<VisibilityHandle | null>(null)
  const registerViewport = useViewportPriority()
  const [rendering, setRendering] = useState(true)
  const [viewportReady, setViewportReady] = useState(() => typeof window === 'undefined')
  const renderIdRef = useRef(0)

  useEffect(() => {
    const el = containerRef.current
    if (!el)
      return
    const handle = registerViewport(el, { rootMargin: '400px' })
    viewportHandleRef.current = handle
    if (handle.isVisible())
      setViewportReady(true)
    handle.whenVisible.then(() => setViewportReady(true))
    return () => {
      handle.destroy()
      viewportHandleRef.current = null
    }
  }, [registerViewport])

  useEffect(() => {
    const content = normalizeKaTeXRenderInput(node.content ?? '')
    if (!content) {
      if (mathRef.current)
        mathRef.current.innerHTML = ''
      setRendering(false)
      return
    }
    if (!viewportReady) {
      setRendering(true)
      return
    }

    let aborted = false
    const controller = new AbortController()
    const renderId = ++renderIdRef.current

    renderKaTeXWithBackpressure(content, true, {
      timeout: 3000,
      waitTimeout: 2000,
      maxRetries: 1,
      signal: controller.signal,
    })
      .then((html) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (mathRef.current)
          mathRef.current.innerHTML = html
        setRendering(false)
      })
      .catch(async (err: any) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (!mathRef.current)
          return
        const code = err?.code || err?.name
        const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || err?.fallbackToRenderer
        const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
        if (isWorkerInitFailure || isBusyOrTimeout) {
          const katex = await getKatex()
          if (katex) {
            try {
              const html = katex.renderToString(content, {
                throwOnError: node.loading,
                displayMode: true,
              })
              if (!aborted && renderId === renderIdRef.current && mathRef.current) {
                mathRef.current.innerHTML = html
                setRendering(false)
                setKaTeXCache(content, true, html)
              }
              return
            }
            catch {}
          }
        }
        if (!node.loading) {
          mathRef.current.textContent = node.raw
          setRendering(false)
        }
      })

    return () => {
      aborted = true
      controller.abort()
    }
  }, [node.content, node.loading, node.raw, viewportReady])

  return (
    <div ref={containerRef} className="math-block text-center overflow-x-auto relative min-h-[40px]">
      <div ref={mathRef} className={rendering ? 'math-rendering' : undefined} />
    </div>
  )
}
