// libs/markstream-vue/packages/markstream-react/src/components/FootnoteAnchorNode/FootnoteAnchorNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback } from 'react'

export function FootnoteAnchorNode(props: NodeComponentProps<{ type: 'footnote_anchor', id: string }>) {
  const { node } = props
  const handleScroll = useCallback((event: React.MouseEvent) => {
    event.preventDefault()
    if (typeof document === 'undefined')
      return
    const target = document.getElementById(`fnref-${String(node.id ?? '')}`)
    if (target)
      target.scrollIntoView({ behavior: 'smooth' })
  }, [node.id])

  return (
    <a
      className="footnote-anchor text-sm text-[#0366d6] hover:underline cursor-pointer"
      href={`#fnref-${node.id}`}
      title={`Back to reference ${node.id}`}
      onClick={handleScroll}
    >
      ↩︎
    </a>
  )
}

export default FootnoteAnchorNode

// libs/markstream-vue/packages/markstream-angular/src/components/FootnoteAnchorNode/FootnoteAnchorNode.component.ts
import type { AngularRenderableNode } from '../shared/node-helpers'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-footnote-anchor-node',
  standalone: true,
  template: `
    <a
      class="footnote-anchor text-sm text-[#0366d6] hover:underline cursor-pointer"
      [attr.href]="href"
      [attr.title]="title"
    >
      ↩︎
    </a>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FootnoteAnchorNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode

  get id() {
    return getString((this.node as any)?.id)
  }

  get href() {
    return `#fnref-${this.id}`
  }

  get title() {
    return `Back to reference ${this.id}`
  }
}
