// libs/markstream-vue/packages/markstream-angular/src/components/LinkNode/LinkNode.component.ts
import type { AfterViewInit, ElementRef, OnChanges, OnDestroy } from '@angular/core'
import type { AngularRenderableNode, AngularRenderContext } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import {
  ChangeDetectionStrategy,
  Component,
  forwardRef,
  Input,
  ViewChild,
} from '@angular/core'
import { hideTooltip, showTooltipForAnchor } from '../../tooltip/singletonTooltip'
import { NestedRendererComponent } from '../NestedRenderer/NestedRenderer.component'
import { getNodeList, getString } from '../shared/node-helpers'
import { TextNodeComponent } from '../TextNode/TextNode.component'

@Component({
  selector: 'markstream-angular-link-node',
  standalone: true,
  imports: [CommonModule, forwardRef(() => NestedRendererComponent), forwardRef(() => TextNodeComponent)],
  template: `
    <a
      *ngIf="!loading; else loadingTpl"
      #anchorEl
      class="link-node"
      [attr.href]="href || null"
      [attr.title]="resolvedShowTooltip ? '' : title"
      [attr.aria-label]="'Link: ' + title"
      target="_blank"
      rel="noopener noreferrer"
      [ngStyle]="cssVars"
      (mouseenter)="onAnchorEnter()"
      (mouseleave)="onAnchorLeave()"
    >
      <markstream-angular-nested-renderer
        *ngIf="hasChildren; else fallbackText"
        [nodes]="children"
        [context]="context"
        [indexPrefix]="nestedPrefix"
      />
      <ng-template #fallbackText>
        <markstream-angular-text-node
          [node]="{ type: 'text', content: fallbackLabel }"
          [context]="context"
          [indexKey]="nestedPrefix + '-fallback'"
        />
      </ng-template>
    </a>

    <ng-template #loadingTpl>
      <span class="link-loading" [ngStyle]="cssVars" aria-hidden="false">
        <span class="link-text-wrapper">
          <span class="link-text">
            <markstream-angular-text-node
              [node]="{ type: 'text', content: fallbackLabel }"
              [context]="context"
              [indexKey]="nestedPrefix + '-loading'"
            />
          </span>
          <span class="link-loading-indicator" aria-hidden="true"></span>
        </span>
      </span>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LinkNodeComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('anchorEl') private anchorRef?: ElementRef<HTMLElement>

  @Input({ required: true }) node!: AngularRenderableNode
  @Input() context?: AngularRenderContext
  @Input() indexKey?: string

  private hovering = false

  get href() {
    return getString((this.node as any)?.href)
  }

  get title() {
    const rawTitle = getString((this.node as any)?.title)
    return rawTitle || this.href
  }

  get loading() {
    return (this.node as any)?.loading === true
  }

  get resolvedShowTooltip() {
    return this.context?.showTooltips !== false
  }

  get children() {
    return getNodeList((this.node as any)?.children)
  }

  get hasChildren() {
    return this.children.length > 0
  }

  get fallbackLabel() {
    return getString((this.node as any)?.text || this.href)
  }

  get nestedPrefix() {
    return `${this.indexKey || 'link'}-inline`
  }

  get cssVars() {
    return {
      '--link-color': '#0366d6',
      '--underline-height': '2px',
      '--underline-bottom': '-3px',
      '--underline-opacity': '0.35',
      '--underline-rest-opacity': '0.175',
      '--underline-duration': '1.6s',
      '--underline-timing': 'ease-in-out',
      '--underline-iteration': 'infinite',
    } as Record<string, string>
  }

  ngAfterViewInit() {
    this.syncTooltip()
  }

  ngOnChanges() {
    this.syncTooltip()
  }

  ngOnDestroy() {
    if (this.hovering)
      hideTooltip(true)
  }

  onAnchorEnter() {
    if (!this.resolvedShowTooltip)
      return

    this.hovering = true
    showTooltipForAnchor(this.anchorRef?.nativeElement || null, this.title, 'top', false, this.context?.isDark)
  }

  onAnchorLeave() {
    if (!this.resolvedShowTooltip)
      return

    this.hovering = false
    hideTooltip()
  }

  private syncTooltip() {
    if (!this.hovering || !this.resolvedShowTooltip)
      return

    showTooltipForAnchor(this.anchorRef?.nativeElement || null, this.title, 'top', true, this.context?.isDark)
  }
}

// libs/markstream-vue/packages/markstream-react/src/components/LinkNode/LinkNode.tsx
import type { ParsedNode } from 'stream-markdown-parser'
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback, useMemo } from 'react'
import { renderNodeChildren } from '../../renderers/renderChildren'
import { hideTooltip, showTooltipForAnchor } from '../../tooltip/singletonTooltip'
import { TextNode } from '../TextNode/TextNode'

export interface LinkNodeStyleProps {
  showTooltip?: boolean
  color?: string
  underlineHeight?: number
  underlineBottom?: number | string
  animationDuration?: number
  animationOpacity?: number
  animationTiming?: string
  animationIteration?: string | number
}

export function LinkNode(props: NodeComponentProps<{
  type: 'link'
  href: string
  title: string | null
  text: string
  children?: ParsedNode[]
  loading?: boolean
}> & LinkNodeStyleProps) {
  const { node, ctx, renderNode, indexKey } = props
  const showTip = props.showTooltip !== false
  const isDark = props.isDark ?? ctx?.isDark

  const cssVars = useMemo(() => {
    const bottom = props.underlineBottom !== undefined
      ? (typeof props.underlineBottom === 'number' ? `${props.underlineBottom}px` : String(props.underlineBottom))
      : '-3px'
    const activeOpacity = props.animationOpacity ?? 0.35
    const restingOpacity = Math.max(0.12, Math.min(activeOpacity * 0.5, activeOpacity))
    return {
      ['--link-color' as any]: props.color ?? '#0366d6',
      ['--underline-height' as any]: `${props.underlineHeight ?? 2}px`,
      ['--underline-bottom' as any]: bottom,
      ['--underline-opacity' as any]: String(activeOpacity),
      ['--underline-rest-opacity' as any]: String(restingOpacity),
      ['--underline-duration' as any]: `${props.animationDuration ?? 1.6}s`,
      ['--underline-timing' as any]: props.animationTiming ?? 'ease-in-out',
      ['--underline-iteration' as any]: typeof props.animationIteration === 'number'
        ? String(props.animationIteration)
        : (props.animationIteration ?? 'infinite'),
    } as React.CSSProperties
  }, [
    props.animationDuration,
    props.animationIteration,
    props.animationOpacity,
    props.animationTiming,
    props.color,
    props.underlineBottom,
    props.underlineHeight,
  ])

  const title = typeof node.title === 'string' && node.title.trim().length > 0
    ? node.title
    : String(node.href ?? '')

  const onAnchorEnter = useCallback((event: React.MouseEvent<HTMLAnchorElement>) => {
    if (!showTip)
      return
    const target = event.currentTarget as HTMLElement | null
    const txt = String(node.title || node.href || node.text || '')
    showTooltipForAnchor(target, txt, 'top', false, { x: event.clientX, y: event.clientY }, isDark)
  }, [isDark, node.href, node.text, node.title, showTip])

  const onAnchorLeave = useCallback(() => {
    if (!showTip)
      return
    hideTooltip()
  }, [showTip])

  if (node.loading) {
    return (
      <span
        className="link-loading inline-flex items-baseline gap-1.5"
        aria-hidden="false"
        style={cssVars}
      >
        <span className="link-text-wrapper relative inline-flex">
          <span className="leading-[normal] link-text">
            <TextNode
              node={{ type: 'text', content: String(node.text ?? '') }}
              ctx={ctx}
              indexKey={`${String(indexKey ?? 'link')}-loading`}
              typewriter={props.typewriter}
            />
          </span>
          <span className="link-loading-indicator" aria-hidden="true" />
        </span>
      </span>
    )
  }

  return (
    <a
      className="link-node"
      href={node.href}
      title={showTip ? '' : title}
      aria-label={`Link: ${title}`}
      target="_blank"
      rel="noopener noreferrer"
      style={cssVars}
      onMouseEnter={onAnchorEnter}
      onMouseLeave={onAnchorLeave}
    >
      {ctx && renderNode
        ? renderNodeChildren(node.children, ctx, String(indexKey ?? 'link'), renderNode)
        : (
            <TextNode
              node={{ type: 'text', content: String(node.text ?? '') }}
              ctx={ctx}
              indexKey={`${String(indexKey ?? 'link')}-fallback`}
              typewriter={props.typewriter}
            />
          )}
    </a>
  )
}

export default LinkNode
