// libs/markstream-vue/packages/markstream-vue2/src/components/InlineCodeNode/InlineCodeNode.vue
<script setup lang="ts">
import { computed, getCurrentInstance, inject, ref, watch } from 'vue-demi'
import { resolveStreamingTextState } from '../TextNode/streamingTextState'

const props = defineProps<{
  node: {
    type: 'inline_code'
    code: string
    raw: string
  }
}>()

const instance = getCurrentInstance()
const attrs = computed<Record<string, unknown>>(() => ((instance?.proxy as any)?.$attrs ?? {}) as Record<string, unknown>)
const inheritedTypewriter = inject<{ value?: boolean } | undefined>('markstreamTypewriter', undefined)
const inheritedTextStreamState = inject<Map<string, string> | undefined>('markstreamTextStreamState', undefined)
const explicitTypewriter = computed<boolean | undefined>(() => {
  const raw = attrs.value.typewriter
  if (raw === '' || raw === true || raw === 'true')
    return true
  if (raw === false || raw === 'false')
    return false
  return undefined
})
const typewriterEnabled = computed(() => {
  if (typeof explicitTypewriter.value === 'boolean')
    return explicitTypewriter.value
  if (typeof inheritedTypewriter?.value === 'boolean')
    return inheritedTypewriter.value
  return true
})
const streamStateKey = computed(() => {
  const raw = attrs.value['index-key'] ?? attrs.value.indexKey
  if (raw == null || raw === '')
    return ''
  return String(raw)
})
const settledCode = ref(props.node.code)
const streamedDelta = ref('')
const streamFadeVersion = ref(0)

function getRenderedContent() {
  return settledCode.value + streamedDelta.value
}

function setFullContent(next: string) {
  settledCode.value = next
  streamedDelta.value = ''
}

function settleStreamedDelta() {
  if (!streamedDelta.value)
    return
  settledCode.value = getRenderedContent()
  streamedDelta.value = ''
}

watch(
  [() => props.node.code, streamStateKey, typewriterEnabled],
  ([next]) => {
    const normalized = String(next ?? '')
    const rendered = getRenderedContent()
    const key = streamStateKey.value
    const previousPersisted = key
      ? inheritedTextStreamState?.get(key)
      : undefined
    const previousContent = previousPersisted ?? rendered

    const nextState = resolveStreamingTextState({
      nextContent: normalized,
      previousContent,
      typewriterEnabled: typewriterEnabled.value,
    })

    settledCode.value = nextState.settledContent
    streamedDelta.value = nextState.streamedDelta
    if (nextState.appended)
      streamFadeVersion.value += 1
    if (key)
      inheritedTextStreamState?.set(key, normalized)
  },
  { immediate: true },
)

watch(
  typewriterEnabled,
  (enabled) => {
    if (enabled)
      return
    setFullContent(getRenderedContent())
  },
)

const streamedDeltaClass = computed(() => (
  streamFadeVersion.value % 2 === 0
    ? 'inline-code-stream-delta--a'
    : 'inline-code-stream-delta--b'
))
</script>

<template>
  <code
    class="inline text-[85%] px-1 py-0.5 rounded font-mono bg-[hsl(var(--secondary))] whitespace-normal break-words max-w-full before:content-[''] after:content-['']"
  >
    <span v-if="settledCode">{{ settledCode }}</span>
    <span
      v-if="streamedDelta"
      class="inline-code-stream-delta" :class="[streamedDeltaClass]"
      @animationend="settleStreamedDelta"
    >
      {{ streamedDelta }}
    </span>
  </code>
</template>

<style scoped>
.inline-code-stream-delta {
  animation-duration: var(--stream-update-fade-duration, var(--typewriter-fade-duration, 900ms));
  animation-timing-function: var(--stream-update-fade-ease, var(--typewriter-fade-ease, ease-out));
  animation-fill-mode: both;
  will-change: opacity;
}
.inline-code-stream-delta--a {
  animation-name: inline-code-stream-update-fade-a;
}
.inline-code-stream-delta--b {
  animation-name: inline-code-stream-update-fade-b;
}

@keyframes inline-code-stream-update-fade-a {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes inline-code-stream-update-fade-b {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@media (prefers-reduced-motion: reduce) {
  .inline-code-stream-delta {
    animation: none !important;
  }
}
</style>

// libs/markstream-vue/packages/markstream-react/src/components/InlineCodeNode/InlineCodeNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import clsx from 'clsx'
import React, { useEffect, useRef, useState } from 'react'
import { resolveStreamingTextUpdate } from '../../utils/streamingTextState'

export function InlineCodeNode(props: NodeComponentProps<{ type: 'inline_code', code: string }>) {
  const { node, children, ctx, indexKey, typewriter } = props
  const content = String(node.code ?? '')
  const typewriterEnabled = typewriter ?? ctx?.typewriter ?? true
  const streamStateKey = indexKey == null || indexKey === ''
    ? ''
    : String(indexKey)
  const [settledContent, setSettledContent] = useState(content)
  const [streamedDelta, setStreamedDelta] = useState('')
  const [streamFadeVersion, setStreamFadeVersion] = useState(0)
  const renderedContentRef = useRef({
    settledContent: content,
    streamedDelta: '',
  })

  const setRenderedContent = (nextSettledContent: string, nextStreamedDelta: string) => {
    renderedContentRef.current = {
      settledContent: nextSettledContent,
      streamedDelta: nextStreamedDelta,
    }
    setSettledContent(nextSettledContent)
    setStreamedDelta(nextStreamedDelta)
  }

  const getRenderedContent = () => {
    const { settledContent, streamedDelta } = renderedContentRef.current
    return settledContent + streamedDelta
  }

  useEffect(() => {
    if (children != null) {
      setRenderedContent('', '')
      return
    }

    const textStreamState = ctx?.textStreamState
    const currentState = renderedContentRef.current
    const persistedContent = streamStateKey
      ? textStreamState?.get(streamStateKey)
      : undefined
    const nextState = resolveStreamingTextUpdate({
      nextContent: content,
      persistedContent,
      currentState,
      typewriterEnabled,
    })

    setRenderedContent(nextState.settledContent, nextState.streamedDelta)
    if (nextState.appended)
      setStreamFadeVersion(version => version + 1)
    if (streamStateKey)
      textStreamState?.set(streamStateKey, content)
  }, [children, content, ctx?.textStreamState, streamStateKey, typewriterEnabled])

  const handleStreamedDeltaAnimationEnd = () => {
    if (!renderedContentRef.current.streamedDelta)
      return
    setRenderedContent(getRenderedContent(), '')
  }

  return (
    <code className="inline-code inline text-[85%] px-1 py-0.5 rounded font-mono bg-[hsl(var(--secondary))] whitespace-normal break-words max-w-full">
      {children || (
        <>
          {settledContent ? <span>{settledContent}</span> : null}
          {streamedDelta
            ? (
                <span
                  className={clsx(
                    'text-node-stream-delta',
                    streamFadeVersion % 2 === 0
                      ? 'text-node-stream-delta--a'
                      : 'text-node-stream-delta--b',
                  )}
                  onAnimationEnd={handleStreamedDeltaAnimationEnd}
                >
                  {streamedDelta}
                </span>
              )
            : null}
        </>
      )}
    </code>
  )
}

export default InlineCodeNode
