// libs/markstream-vue/packages/markstream-react/src/components/ImageNode/ImageNode.tsx
import type { ImageNodeProps } from '../../types/component-props'
import React, { useEffect, useState } from 'react'

const DEFAULT_PROPS = {
  fallbackSrc: '',
  lazy: true,
  usePlaceholder: true,
}

export interface ImageNodeReactEvents {
  onLoad?: (src: string) => void
  onError?: (src: string) => void
  onClick?: (payload: [event: React.MouseEvent<HTMLImageElement>, src: string]) => void
}

export function ImageNode(rawProps: ImageNodeProps & ImageNodeReactEvents) {
  const props = { ...DEFAULT_PROPS, ...rawProps }
  const [imageLoaded, setImageLoaded] = useState(false)
  const [hasError, setHasError] = useState(false)
  const [fallbackTried, setFallbackTried] = useState(false)

  const displaySrc = hasError && props.fallbackSrc
    ? props.fallbackSrc
    : props.node.src

  useEffect(() => {
    setImageLoaded(false)
    setHasError(false)
  }, [displaySrc])

  useEffect(() => {
    setFallbackTried(false)
  }, [props.node.src])

  const handleImageError = () => {
    if (props.fallbackSrc && !fallbackTried) {
      setFallbackTried(true)
      setHasError(true)
    }
    else {
      setHasError(true)
      props.onError?.(props.node.src)
    }
  }

  const handleImageLoad = () => {
    setImageLoaded(true)
    setHasError(false)
    props.onLoad?.(displaySrc)
  }

  const handleClick = (event: React.MouseEvent<HTMLImageElement>) => {
    event.preventDefault()
    if (!imageLoaded || hasError) {
      return
    }
    props.onClick?.([event, displaySrc])
  }

  if (!props.node.loading && !hasError) {
    return (
      <img
        key="image"
        src={displaySrc}
        alt={String(props.node.alt ?? props.node.title ?? '')}
        title={String(props.node.title ?? props.node.alt ?? '')}
        className={`image-node__img${imageLoaded ? ' is-loaded' : ''}`}
        loading={props.lazy ? 'lazy' : 'eager'}
        decoding="async"
        tabIndex={imageLoaded ? 0 : -1}
        aria-label={props.node.alt ?? 'Preview image'}
        onError={handleImageError}
        onLoad={handleImageLoad}
        onClick={handleClick}
      />
    )
  }

  if (!hasError) {
    return (
      <span key="placeholder" className="image-node__placeholder">
        {props.usePlaceholder
          ? (
              <>
                <span className="image-node__spinner" aria-hidden="true" />
                <span className="image-node__placeholder-text">Loading image...</span>
              </>
            )
          : (
              <span className="image-node__placeholder-text">{props.node.raw ?? 'Loading image…'}</span>
            )}
      </span>
    )
  }

  if (!props.node.loading && !props.fallbackSrc) {
    return (
      <span className="image-node__error">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            fill="currentColor"
            d="M2 2h20v10h-2V4H4v9.586l5-5L14.414 14L13 15.414l-4-4l-5 5V20h8v2H2zm13.547 5a1 1 0 1 0 0 2a1 1 0 0 0 0-2m-3 1a3 3 0 1 1 6 0a3 3 0 0 1-6 0m3.625 6.757L19 17.586l2.828-2.829l1.415 1.415L20.414 19l2.829 2.828l-1.415 1.415L19 20.414l-2.828 2.829l-1.415-1.415L17.586 19l-2.829-2.828z"
          />
        </svg>
        <span className="image-node__placeholder-text">Image failed to load</span>
      </span>
    )
  }

  return null
}

export default ImageNode

// libs/markstream-vue/packages/markstream-vue2/src/components/ImageNode/ImageNode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue-demi'
import { useSafeI18n } from '../../composables/useSafeI18n'

interface ImageNodeProps {
  node: {
    type: 'image'
    src: string
    alt: string
    title: string | null
    raw: string
    loading?: boolean
  }
  fallbackSrc?: string
  lazy?: boolean
  usePlaceholder?: boolean
}

const props = withDefaults(defineProps<ImageNodeProps>(), {
  fallbackSrc: '',
  lazy: true,
  usePlaceholder: true,
})

const emit = defineEmits<{ (e: 'load', src: string): void, (e: 'error', src: string): void, (e: 'click', payload: [Event, string]): void }>()

const imageLoaded = ref(false)
const hasError = ref(false)
const fallbackTried = ref(false)
const displaySrc = computed(() => hasError.value && props.fallbackSrc ? props.fallbackSrc : props.node.src)

function handleImageError() {
  if (props.fallbackSrc && !fallbackTried.value) {
    fallbackTried.value = true
    hasError.value = true
    // leave imageLoaded false so placeholder/spinner can show while fallback loads
  }
  else {
    hasError.value = true
    emit('error', props.node.src)
  }
}

function handleImageLoad() {
  imageLoaded.value = true
  hasError.value = false
  emit('load', displaySrc.value)
}

function handleClick(e: Event) {
  e.preventDefault()

  if (!imageLoaded.value || hasError.value)
    return
  emit('click', [e, displaySrc.value])
}

const { t } = useSafeI18n()

watch(displaySrc, () => {
  imageLoaded.value = false
  hasError.value = false
})
</script>

<template>
  <transition name="img-switch" mode="out-in">
    <img
      v-if="!node.loading && !hasError"
      key="image"
      :src="displaySrc"
      :alt="String(props.node.alt ?? props.node.title ?? '')"
      :title="String(props.node.title ?? props.node.alt ?? '')"
      class="image-node__img h-auto rounded-lg transition-opacity duration-200 ease-in-out image-node__img--inline"
      :class="{
        'opacity-0': !imageLoaded,
        'opacity-100': imageLoaded,
        'cursor-pointer': imageLoaded,
      }"
      :loading="props.lazy ? 'lazy' : 'eager'"
      decoding="async"
      :tabindex="imageLoaded ? 0 : -1"
      :aria-label="props.node.alt ?? t('image.preview')"
      @error="handleImageError"
      @load="handleImageLoad"
      @click="handleClick"
    >

    <span
      v-else-if="!hasError"
      key="placeholder"
      class="placeholder-layer placeholder-layer--inline inline-flex items-center justify-center gap-2"
    >
      <template v-if="props.usePlaceholder">
        <slot name="placeholder" :node="props.node" :display-src="displaySrc" :image-loaded="imageLoaded" :has-error="hasError" :fallback-src="props.fallbackSrc" :lazy="props.lazy">
          <div class="w-4 h-4 rounded-full border-2 border-solid border-current border-t-transparent animate-spin" aria-hidden="true" />
          <span class="text-sm whitespace-nowrap">{{ t('image.loading') }}</span>
        </slot>
      </template>
      <template v-else>
        <span class="text-sm text-gray-500">{{ node.raw }}</span>
      </template>
    </span>

    <span v-else-if="!node.loading && !props.fallbackSrc" key="error" class="image-node__error image-node__error--inline px-4 py-2 bg-gray-100 flex items-center justify-center rounded-lg gap-2 text-red-500">
      <slot name="error" :node="props.node" :display-src="displaySrc" :image-loaded="imageLoaded" :has-error="hasError" :fallback-src="props.fallbackSrc" :lazy="props.lazy">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><!-- Icon from TDesign Icons by TDesign - https://github.com/Tencent/tdesign-icons/blob/main/LICENSE --><path fill="currentColor" d="M2 2h20v10h-2V4H4v9.586l5-5L14.414 14L13 15.414l-4-4l-5 5V20h8v2H2zm13.547 5a1 1 0 1 0 0 2a1 1 0 0 0 0-2m-3 1a3 3 0 1 1 6 0a3 3 0 0 1-6 0m3.625 6.757L19 17.586l2.828-2.829l1.415 1.415L20.414 19l2.829 2.828l-1.415 1.415L19 20.414l-2.828 2.829l-1.415-1.415L17.586 19l-2.829-2.828z" /></svg>
        <span class="text-sm whitespace-nowrap">{{ t('image.loadError') }}</span>
      </slot>
    </span>
  </transition>
</template>

<style scoped>
.image-node__img {
  max-width: 24rem;
}

.placeholder-layer {
  max-width: 24rem;
}

.image-node__img--inline {
  min-height: 0 !important;
  width: auto !important;
  height: auto !important;
  object-fit: initial !important;
  display: inline-block;
  vertical-align: middle;
}

.placeholder-layer--inline {
  min-height: auto !important;
}

.image-node__error--inline {
  display: inline-flex;
  vertical-align: middle;
}

.img-switch-enter-active, .img-switch-leave-active {
  transition: opacity 220ms ease, transform 220ms ease;
}
.img-switch-enter-from, .img-switch-leave-to {
  opacity: 0;
  transform: translateY(6px);
}
.img-switch-enter-to, .img-switch-leave-from {
  opacity: 1;
  transform: translateY(0);
}

.placeholder-layer {
  will-change: transform, opacity;
}

@media (prefers-reduced-motion: reduce) {
  .spinner { animation: none !important; }
  .img-switch-enter-active, .img-switch-leave-active { transition: none !important; }
}
</style>
