// libs/markstream-vue/packages/markstream-angular/src/components/PreCodeNode/PreCodeNode.component.ts
import type { AngularRenderableNode } from '../shared/node-helpers'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { getString, normalizeCodeLanguage } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-pre-code-node',
  standalone: true,
  template: `<pre [class]="languageClass" [attr.aria-busy]="loading" [attr.aria-label]="ariaLabel" [attr.data-language]="language" tabindex="0"><code translate="no" [textContent]="code"></code></pre>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PreCodeNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode

  get language() {
    return normalizeCodeLanguage((this.node as any)?.language)
  }

  get languageClass() {
    return `language-${this.language}`
  }

  get ariaLabel() {
    return this.language ? `Code block: ${this.language}` : 'Code block'
  }

  get code() {
    return getString((this.node as any)?.code)
  }

  get loading() {
    return (this.node as any)?.loading === true
  }
}

// libs/markstream-vue/packages/markstream-react/src/components/CodeBlockNode/PreCodeNode.tsx
import type { PreCodeNodeProps } from '../../types/component-props'
import React, { useMemo } from 'react'

function normalizeLanguage(raw: unknown) {
  const head = String(String(raw ?? '').split(/\s+/g)[0] ?? '').toLowerCase()
  const safe = head.replace(/[^\w-]/g, '')
  return safe || 'plaintext'
}

export function PreCodeNode({ node }: PreCodeNodeProps) {
  const normalizedLanguage = useMemo(() => normalizeLanguage((node as any)?.language), [node])
  const languageClass = `language-${normalizedLanguage}`
  const ariaLabel = normalizedLanguage ? `Code block: ${normalizedLanguage}` : 'Code block'

  return (
    <pre
      className={languageClass}
      aria-busy={(node as any)?.loading === true}
      aria-label={ariaLabel}
      data-language={normalizedLanguage}
      tabIndex={0}
    >
      <code translate="no">{String((node as any)?.code ?? '')}</code>
    </pre>
  )
}
